In [30]:
from bs4 import BeautifulSoup
from nltk.tokenize import word_tokenize, sent_tokenize
import cltk
import pandas as pd
import numpy as np
import os

## Formatting text (XML to Tuple of desired attributes)

In [2]:
def desoupify(fileloc):
    #Creates soup object
    with open( fileloc, 'r') as f:
        file = f.read() 
    xml_soup = BeautifulSoup(file,'xml')
    
#grabs text from the object 
    text_soup = xml_soup.find_all("p")
   
    length = len(text_soup)
    if length == 0:
        text_soup = xml_soup.find_all("l")

#joins into text
    text = []
    for x in text_soup: 
        text.append(x.text)
    text = ' '.join(text)
    return text

In [3]:
def text_clear(text):

#converts all characters to lower case 
    string = text.lower()

    string = string.replace("\n"," ")

#cleans out punctuation
    punc = '''()-[]{};:'"\,<>/@,#$%^&,:*_~'''
    for sym in string:
        if sym in punc:
            string = string.replace(sym,"")
    string = string.replace('keyboarding','')
    return string

In [4]:
#tokenizes
def tokenizer_pipline(string): 
    finished = []
    string = sent_tokenize(string)
    for x in string: 
        finished.append(word_tokenize(x))
        
    return finished

In [5]:
#Creates tuples of desired atrributes
def attributor(directory,period): 
    final = []
    
    for filename in os.listdir(directory)[1:]:
        f = os.path.join(directory, filename)
        ready = tokenizer_pipline(text_clear(desoupify(f)))
        for x in ready: 
            y =' '.join(x)
            final.append((directory,period,filename,x,y))
    return final

## Tuples to Dataframe

In [6]:
data = attributor('Virgil','Golden')

In [7]:
# Creating a DataFrame
df = pd.DataFrame(data,columns=['Author','Period','Work','Tokenized Text', 'Untokenized Text'])

df.head(1)

,Author,Period,Work,Tokenized Text,Untokenized Text
0,Virgil,Golden,Aeneid,"[arma, virumque, cano, troiae, qui, primus, ab...",arma virumque cano troiae qui primus ab oris i...
1,Virgil,Golden,Aeneid,"[musa, mihi, causas, memora, quo, numine, laes...",musa mihi causas memora quo numine laeso quidv...
2,Virgil,Golden,Aeneid,"[tantaene, animis, caelestibus, irae, ?]",tantaene animis caelestibus irae ?
3,Virgil,Golden,Aeneid,"[urbs, antiqua, fuit, tyrii, tenuere, coloni, ...",urbs antiqua fuit tyrii tenuere coloni karthag...
4,Virgil,Golden,Aeneid,"[progeniem, sed, enim, troiano, a, sanguine, d...",progeniem sed enim troiano a sanguine duci aud...
...,...,...,...,...,...
3259,Virgil,Golden,Aeneid,"[vicisti, et, victum, tendere, palmas, ausonii...",vicisti et victum tendere palmas ausonii vider...
3260,Virgil,Golden,Aeneid,"[stetit, acer, in, armis, aeneas, volvens, ocu...",stetit acer in armis aeneas volvens oculos dex...
3261,Virgil,Golden,Aeneid,"[ille, oculis, postquam, saevi, monimenta, dol...",ille oculis postquam saevi monimenta doloris e...
3262,Virgil,Golden,Aeneid,"[pallas, te, hoc, volnere, pallas, immolat, et...",pallas te hoc volnere pallas immolat et poenam...
3263,Virgil,Golden,Aeneid,"[ast, illi, solvuntur, frigore, membra, vitaqu...",ast illi solvuntur frigore membra vitaque cum ...